### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by GolferChen** [BAI-Yeqi/SF2F_PyTorch#1]
Hello, very nice work and helpful codes. I wonder would you please release the pre-trained models.

**Comment by BAI-Yeqi** [comment]
Hi, thank you for your interest in our work. I have checked with our funding agency and they cannot agree to release the pretrained weights at this moment.

We'd like to encourage you to train the models from scratch if you intend to test out our method.

Please adhere to our [LICENSE](https://github.com/BAI-Yeqi/SF2F_PyTorch/blob/main/LICENSE) while using our method.
