### ISSUE TITLE
full_vox2_meta.csv

### ISSUE THREAD

**Issue by GolferChen** [BAI-Yeqi/SF2F_PyTorch#2]
Hello, thanks for your code again. I have the following problem when running the code:

The file `convert_wav_to_mel.py` depends on the file `full_vox2_meta.csv`. However, I cannot find it on the official website of VoxCeleb2. The only available file is `vox2_meta.csv` instead, which unfortunately cannot be used to replace `full_vox2_meta.csv` because `vox2_meta.csv` does not have the identity names (see below), which I think are necessary for matching voices and faces in your provided dataset HQ-VoxCeleb.

Would you share this file with me or tell me where to download it? Many thanks for your help in advance. 

![image](https://user-images.githubusercontent.com/47413995/219315516-cb5ffe92-ff0f-4d32-b6c0-058335689251.png)

**Comment by BAI-Yeqi** [comment]
@GolferChen Thank you for the great question. You can download it from [HQ-VoxCeleb Repo](https://github.com/BAI-Yeqi/HQ-VoxCeleb/blob/main/meta_info).

**Comment by GolferChen** [comment]
@BAI-Yeqi Thanks a lot. 👍
